### ISSUE TITLE
`require_component': could not resolve require file 

### ISSUE THREAD

**Issue by adragoset** [dry-rb/dry-component#16]
Container Definition:
```
# frozen_string_literal: true
require 'dry/component/container'

module Dependencies
  # The Ioc Container for the app
  class Container < Dry::Component::Container

    configure do |config|
      config.root = Pathname.new('./alertbus')
    end
  end
end
```

Dependency Declaration:
```
# frozen_string_literal: true
require 'dry/component/container'
require './app/services/fae_email_notifier'
require './config/initializers/dependencies/container'

module Dependencies
  #register app_config variables
  Dependencies::Container.register(
    :dashboard_domain, -> { APP_CONFIG[:dashboard_url] })
  Dependencies::Container.register(
    :mailer_domain, -> { APP_CONFIG[:mailer_domain] })

  #register services
  Dependencies::Container.register(
    'services.fae_email_notifier',
    Services::FaeEmailNotifier.new(
    dashboard_domain: 'test',
    mailer_domain: 'test')
  )

  Application_Container = Dependencies::Container::Inject
end
```
Injection in use:
```
# frozen_string_literal: true
# This workers converts transcodes zips and notifies personnel about FAE
# video requests that have been completed.
module Services
class FaeVideoRequestWorker < BaseWorker
  include Dependencies::Application_Container['services.fae_email_notifier']
```

Error:
```
container.rb:163:in `require_component': could not resolve require file for services.fae_email_notifier
```

So i had this rather simple bit of code working before the latest version bump when import_module was removed from DryContainer and replaced with the Inject method. Notice how its really not much more complex than the dry-component example docs on the dry-component webpage. Now im getting errors when running the test for the associated worker code which is the only thing using dry atm. Want to add that the dry component documentation is now wrong on http://dry-rb.org/gems/dry-component. I think what dry is lacking right now is detailed documentation on how to get it set up on applications in practice. Which makes it rather difficult to use especially when the api is changing heavily and use documentation is not kept up to date.

**Comment by timriley** [comment]
Thanks for the report, @adragoset! I'm sorry about the docs – I'll update them this morning.

As for your example, though – I can't actually replicate it. Here's a slightly simplified version that works for me:

```ruby
require "dry/component/container"

module Dependencies
  # The Ioc Container for the app
  class Container < Dry::Component::Container

    configure do |config|
      config.root = Pathname.new('./alertbus')
    end
  end
end

module Dependencies
  Dependencies::Container.register 'services.fae_email_notifier', "This would be a Services::FaeEmailNotifier"

  Application_Container = Dependencies::Container::Inject
end

class MyClass
  include Dependencies::Application_Container["services.fae_email_notifier"]
end

my_obj = MyClass.new
# => #<MyClass:0x007f89a5c8d350 @fae_email_notifier="This would be a Services::FaeEmailNotifier">
```

I'm wondering if perhaps you're trying to access the `"services.fae_email_notifier"` dependency (i.e. from an injection in another class) before you've registered it? If there's no matching source file for that name (e.g. `services/fae_email_notifier.rb`), then this is the situation where I could see your error occurring. 

Alternatively, perhaps you're missing a `load_paths!` line in your container? This would be another reason that a file could not be found – if it's inside some load path that the container is not aware of. Here's how most of our containers are set up:

```ruby
module Main
  class Container < Dry::Component::Container
    configure do |config|
      config.root = Pathname(__FILE__).join("../..").realpath.dirname.freeze

      config.auto_register = %w[
        lib/main
      ]
    end

    load_paths! "lib", "core"
  end
end
```

**Comment by adragoset** [comment]
Thanks for the quick reply. I think your right about it trying to be accessed before it gets initialized. Currently 
```
module Dependencies
  Dependencies::Container.register 'services.fae_email_notifier', "This would be a Services::FaeEmailNotifier"

  Application_Container = Dependencies::Container::Inject
end
```

is in a file defined in rails initializers folder. The failure is occuring when i run the spec for the class needing the injected dependency. Additionally i dont think dry would be aware of my service/fae_email_notifier.rb as its in the app/services folder which is fine because im not ready to start auto loading classes for injection. At any rate i was hoping a rails would initialize my container dependencies during specs and when the app starts. I think this may be an issue with how and where im trying to initialize the container within my rails application.

**Comment by timriley** [comment]
No worries, @adragoset :) I'll close this for now, but please comment again or reopen if you learn anything more!

I've also update the dry-rb.org docs to show the new `MyContainer::Inject` API in use.

**Comment by adragoset** [comment]
This is an interesting one. You were correct in there being an additional call to the container. For some reason the rspec test for this class was injecting the dependency into itself most likely before the configuration ran and set up the containers manually with the .require calls. 

A couple of tweaks to the rspec tests mocking the service object and it's working again. Thanks for the help. Hopefully i can start using dry more in this huge mess of an rails app i inherited. Maybe ill have some stuff to contribute in the future as i start using more of the features of dry-component.
